Add support for cancellations in RCP 3.0+. #4
TomodomoCo/rcp-stripe-elements pull request #5
Opened 2019-03-04 16:41 UTC by nosegraze

Closes #4

2019-03-04 17:46 UTC, mcfarlan commented
Thanks so much Ashley for getting this shipped! We'll get this merged shortly. Much appreciated!

2019-03-04 19:26 UTC, chrisvanpatten requested changes
Thanks @nosegraze! I caught two small things, but want to note that we in no way expect you to make those changes. We're happy to correct those on our end before we merge. Thank you SO much for submitting the change. To be honest it's nice to hear people are using this in production!

2019-03-04 19:26 UTC, chrisvanpatten commented on rcp-stripe-elements.php
> +	if ( 'stripe_elements' != $membership->get_gateway() ) {
Would like to see this as a strict equality check (`!==`), and also a non-yoda condition

2019-03-04 19:26 UTC, chrisvanpatten commented on rcp-stripe-elements.php
> +	if ( 'stripe_elements' != $gateway ) {
Strict check, but also potentially combine to `if ( $success || $gateway !== 'stripe_elements' )`

2019-03-05 09:06 UTC, nosegraze commented
No problem - updated. :)

2019-03-05 15:57 UTC, chrisvanpatten approved these changes

2019-03-05 15:58 UTC, merged